package ir_test

// This is the Phase 2 correctness gate: the byte-identical round-trip oracle.
// It lives in the EXTERNAL test package (ir_test) on purpose — it is the only
// place that wires the concrete zsh.Provider to the agnostic core/ir, so the
// production ir package stays shell-free. It executes the ORIGINAL and the
// REGENERATED .zsh each under sandboxed `zsh -f` (no rc files, 5s timeout, via
// the reused Provider.Introspect instrument), snapshots the resolved
// model.IdentitySet, and asserts the two are equal across all 5 declarative
// classes (D-08). Skip-guarded for zsh-absent environments.

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"testing"

	"zsh-pro/core/ir"
	"zsh-pro/core/shell/zsh"
)

// TestRegenRoundTrip proves the IR regenerates behavior-equivalent zsh: the
// runtime state after sourcing the regenerated config is byte-identical to the
// runtime state after sourcing the original, with dynamic values late-bound
// verbatim (never resolved against this machine).
func TestRegenRoundTrip(t *testing.T) {
	if _, err := exec.LookPath("zsh"); err != nil {
		t.Skip("zsh not installed; skipping round-trip oracle")
	}

	// Representative fixture covering ALL 5 declarative classes:
	//   static env, dynamic env, dynamic PATH, alias, option, function.
	// A real PATH assignment exercises the $path snapshot (#1). Deliberately NO
	// compinit/zstyle/autoload — keep the oracle deterministic (Pitfall 4).
	src := []byte("export EDITOR=nvim\n" +
		"export GOPATH=$HOME/go\n" +
		"export PATH=$HOME/bin:$PATH\n" +
		"alias gs='git status'\n" +
		"setopt EXTENDED_GLOB\n" +
		"greet() { echo hi }\n")

	p := zsh.Provider{}
	blocks, _ := p.Parse(src)
	profile := ir.Build(blocks, p)
	regen := ir.Regenerate(profile, p)

	dir := t.TempDir()
	origPath := filepath.Join(dir, "orig.zsh")
	regenPath := filepath.Join(dir, "regen.zsh")
	if err := os.WriteFile(origPath, src, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(regenPath, regen, 0o644); err != nil {
		t.Fatal(err)
	}

	// Separate error variables (#5): a second-call failure must never surface as
	// a confusing nil panic or shared-err ambiguity.
	origIDS, origErr := p.Introspect(origPath)
	regenIDS, regenErr := p.Introspect(regenPath)

	if origErr != nil || !origIDS.Available {
		t.Fatalf("introspect(original) failed: err=%v available=%v", origErr, origIDS.Available)
	}
	if regenErr != nil || !regenIDS.Available {
		t.Fatalf("introspect(regenerated) failed: err=%v available=%v\nregen=%q", regenErr, regenIDS.Available, regen)
	}

	// Byte-identical state tables across all 5 declarative classes (D-08).
	if !reflect.DeepEqual(origIDS.Aliases, regenIDS.Aliases) {
		t.Errorf("Aliases differ:\n orig=%v\n regen=%v\nsrc=%q\nregen=%q", origIDS.Aliases, regenIDS.Aliases, src, regen)
	}
	if !reflect.DeepEqual(origIDS.Functions, regenIDS.Functions) {
		t.Errorf("Functions differ:\n orig=%v\n regen=%v\nsrc=%q\nregen=%q", origIDS.Functions, regenIDS.Functions, src, regen)
	}
	if !reflect.DeepEqual(origIDS.Env, regenIDS.Env) {
		t.Errorf("Env differ:\n orig=%v\n regen=%v\nsrc=%q\nregen=%q", origIDS.Env, regenIDS.Env, src, regen)
	}
	if !reflect.DeepEqual(origIDS.Options, regenIDS.Options) {
		t.Errorf("Options differ:\n orig=%v\n regen=%v\nsrc=%q\nregen=%q", origIDS.Options, regenIDS.Options, src, regen)
	}
	if !reflect.DeepEqual(origIDS.Path, regenIDS.Path) {
		t.Errorf("Path differ:\n orig=%v\n regen=%v\nsrc=%q\nregen=%q", origIDS.Path, regenIDS.Path, src, regen)
	}

	// Class-presence sanity: the function and the option must actually be present
	// in BOTH snapshots (proves templated-function + templated-setopt regeneration,
	// not two empty-but-equal tables).
	if !origIDS.Functions["greet"] || !regenIDS.Functions["greet"] {
		t.Errorf("greet absent from a snapshot (templated-function regen not proven): orig=%v regen=%v", origIDS.Functions, regenIDS.Functions)
	}
	if !origIDS.Options["extendedglob"] || !regenIDS.Options["extendedglob"] {
		t.Errorf("extendedglob option absent from a snapshot (templated-setopt regen not proven): orig=%v regen=%v", origIDS.Options, regenIDS.Options)
	}

	// EVAL-01 SC3: GOPATH (driven by $HOME/go) present in both Env snapshots
	// (late-bound identically), and the regenerated bytes still carry the LITERAL
	// dynamic values — never the resolved absolute path.
	if !origIDS.Env["GOPATH"] || !regenIDS.Env["GOPATH"] {
		t.Errorf("GOPATH absent from a snapshot (dynamic env round-trip not proven): orig=%v regen=%v", origIDS.Env, regenIDS.Env)
	}
	if !bytes.Contains(regen, []byte("$HOME/go")) {
		t.Errorf("dynamic value resolved: regenerated bytes do not contain literal $HOME/go: %q", regen)
	}
	if !bytes.Contains(regen, []byte("$HOME/bin:$PATH")) {
		t.Errorf("dynamic PATH resolved: regenerated bytes do not contain literal $HOME/bin:$PATH: %q", regen)
	}
}
